# Generated by Django 5.1.15 on 2025-12-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DraftRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=36, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blue_captain', models.CharField(blank=True, max_length=100, null=True)),
                ('red_captain', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for captains'), ('drafting', 'Draft in progress'), ('finished', 'Finished')], default='waiting', max_length=20)),
            ],
        ),
    ]
