# Generated by Django 5.1.15 on 2025-12-29 19:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lold', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftroom',
            name='current_turn',
            field=models.CharField(choices=[('blue', 'Blue'), ('red', 'Red')], default='blue', max_length=10),
        ),
        migrations.AlterField(
            model_name='draftroom',
            name='blue_captain',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='draftroom',
            name='red_captain',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='draftroom',
            name='room_id',
            field=models.CharField(default=uuid.uuid4, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='draftroom',
            name='status',
            field=models.CharField(choices=[('waiting', 'Ожидание капитанов'), ('banning', 'Фаза банов'), ('picking', 'Фаза пиков'), ('finished', 'Завершено')], default='waiting', max_length=20),
        ),
        migrations.CreateModel(
            name='ChampionAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champion_name', models.CharField(max_length=50)),
                ('action_type', models.CharField(choices=[('ban', 'Ban'), ('pick', 'Pick')], max_length=10)),
                ('side', models.CharField(choices=[('blue', 'Blue'), ('red', 'Red')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='lold.draftroom')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
