# Generated by Django 5.1.15 on 2025-12-29 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lold', '0003_alter_draftroom_blue_captain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftroom',
            name='blue_captain',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='draftroom',
            name='red_captain',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
