# Generated by Django 5.2.9 on 2026-01-08 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lold', '0004_alter_draftroom_blue_captain_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BanPhase',
            fields=[
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='lold.draftroom')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name=models.CharField(max_length=100))),
            ],
        ),
        migrations.CreateModel(
            name='PickPhase',
            fields=[
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='lold.draftroom')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name=models.CharField(max_length=100))),
            ],
        ),
        migrations.RemoveField(
            model_name='draftroom',
            name='current_turn',
        ),
        migrations.AlterField(
            model_name='draftroom',
            name='status',
            field=models.CharField(choices=[('waiting', 'waiting'), ('select_side', 'select_side'), ('ban_phase', 'ban_phase'), ('pick_phase', 'pick_phase')], default='waiting', max_length=100),
        ),
        migrations.DeleteModel(
            name='ChampionAction',
        ),
    ]
