# Generated by Django 5.2.9 on 2026-01-08 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lold', '0005_banphase_pickphase_remove_draftroom_current_turn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banphase',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='pickphase',
            name='tags',
        ),
        migrations.AddField(
            model_name='banphase',
            name='champions_Blue_team',
            field=models.JSONField(blank=True, default=list, verbose_name=models.CharField(max_length=100)),
        ),
        migrations.AddField(
            model_name='banphase',
            name='champions_Red_team',
            field=models.JSONField(blank=True, default=list, verbose_name=models.CharField(max_length=100)),
        ),
        migrations.AddField(
            model_name='pickphase',
            name='champions_Blue_team',
            field=models.JSONField(blank=True, default=list, verbose_name=models.CharField(max_length=100)),
        ),
        migrations.AddField(
            model_name='pickphase',
            name='champions_Red_team',
            field=models.JSONField(blank=True, default=list, verbose_name=models.CharField(max_length=100)),
        ),
    ]
