# Generated by Django 5.2.9 on 2026-01-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lold', '0006_remove_banphase_tags_remove_pickphase_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftroom',
            name='status',
            field=models.CharField(blank=True, default='waiting', max_length=100),
        ),
    ]
