# Generated by Django 5.2.9 on 2026-01-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lold', '0007_alter_draftroom_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftroom',
            name='cur_turn',
            field=models.CharField(blank=True, default='waiting', max_length=10),
        ),
        migrations.AlterField(
            model_name='draftroom',
            name='status',
            field=models.CharField(blank=True, default='waiting', max_length=10),
        ),
    ]
