# Generated by Django 5.2.9 on 2026-01-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lold', '0008_draftroom_cur_turn_alter_draftroom_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftroom',
            name='turn_index',
            field=models.IntegerField(default=1),
        ),
    ]
