# Generated by Django 5.2.7 on 2026-01-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lold', '0009_draftroom_turn_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftroom',
            name='turn_index',
            field=models.IntegerField(default=0),
        ),
    ]
